name: Forge 1.12.2 Cache Builder

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'  # Parameter wajib yang hilang
        java-package: jdk
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true
        job-status: success
        cache: 'gradle'

    - name: Build Cache
      run: |
        chmod +x gradlew
        ./gradlew setupDecompWorkspace --no-daemon --stacktrace
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: forge-1.12.2-cache
        path: |
          .gradle/caches/forge_gradle/
          .gradle/caches/modules-2/
        compression-level: 9
        retention-days: 3  # Otomatis hapus setelah 3 hari
